### PR TITLE
swupd.zsh: Updated to support 3rd-party repo

### PR DESCRIPTION
**Pull request by lebensterben**
- Added supports to 3rd-party repos.
- Added a new functionality to complete `version` number. For example
  `swupd update --version=VERSION_NUMBER`
- Updated descriptions for arguments/options.
- Large amount of refactoring. Separation of data and logic.

Various completions for 3rd-party repo won't work with non-root users until we made `/var/lib/swupd/` readable.
See https://github.com/clearlinux/swupd-client/issues/1496

### CODE REVIEW

**Comment by lebensterben** [comment]
Hold on. I've another commit coming. I will probably close this one and made a PR from another branch.

**Comment by lebensterben** [comment]
@otaviobp 
In this latest commit, I separated the data from the logic of the completion scripts.
Now the arguments, options, and their descriptions are declared in the beginning of the script.

**Comment by lebensterben** [comment]
@otaviobp 
I'm considering to write a "contribution guide" for the shell completions of `swupd-client`. (Not in this PR). And it may fit into the `wiki` section of this repository.

This is especially helpful to prevent bugs when a maintainer update the `zsh` script, since it's becoming rather complex now.

What do you think?

**Comment by otaviobp** [comment]
> I'm considering to write a "contribution guide" for the shell completions of swupd-client. (Not in this PR). And it may fit into the wiki section of this repository.

Cool. that would be very nice

**Pull request merged**
