### PR TITLE
Don't accept trailing characters when validating numbers for --format

### LINKED ISSUE #142: Input validation bug for --format
If I supply an invalid value as input to --format, regardless of subcommand, I expect swupd to always exit with an error at the validation step. However, it appears that certain values slip through the input validation, which should only permit positive integer values, or the special string "staging".

```
# swupd update --format 7F
swupd-client software update 3.6.5
   Copyright (C) 2012-2016 Intel Corporation

Attempting to download version string to memory
Error: Network issue, unable to proceed with update
Update took 0 seconds
```

### PR DESCRIPTION
**Pull request by cmarcelo**
Fixes #142.

Signed-off-by: Caio Marcelo de Oliveira Filho <caio.oliveira@intel.com>

### CODE REVIEW

**Comment by matthewrsj** [comment]
+1 for the change.

Please update the commit message to explain why this change was necessary. e.g. strtoull saves invalid trailing characters to endptr and will not set errno when leading characters represent a valid number.

**Comment by matthewrsj** [comment]
**accidentally closed the PR, sorry**

**Comment by phmccarty** [comment]
+1

**Comment by matthewrsj** [comment]
thanks @cmarcelo!

**Pull request merged**
