### PR TITLE
manpages: add return-code documentation

### LINKED ISSUE #296: Improve return code documentation
Right now https://github.com/clearlinux/swupd-client/blob/master/include/swupd-error.h is the only place swupd return codes are "documented". These return codes should be added to the man pages.

### PR DESCRIPTION
**Pull request by matthewrsj**
Additionally remove the unused EPREP_MOUNT error code.
Fixes #296

Signed-off-by: Matthew Johnson <matthew.johnson@intel.com>

### CODE REVIEW

**Comment by otaviobp** [comment]
+1. That's a great improvement to the docs

**Comment by otaviobp** [comment]
The file docs/swupd.1 is generated automatically, right? Can't we remove it from the repository, along with the other manpages?

**Comment by matthewrsj** [comment]
Read discussion here: https://github.com/clearlinux/swupd-client/issues/316

**Comment by icarus-sparry** [comment]
Yes it is generated. No you can not remove it, as we do not require people building from scratch to have the tool to do the generation. Ah, I see @matthewrsj beat me to adding the reference.

**Comment by otaviobp** [comment]
My bad. I didn't know about that discussion. It's ok then

**Pull request merged**
