### PR TITLE
Add new bundle-list sub-command

### PR DESCRIPTION
**Pull request by MarioCarrilloA**
This group of patches add a new sub-command to swupd "bundle-list", this sub-command allows to show which bundles are installed in the local system.

### CODE REVIEW

**Comment by sofar** [comment]
Please also update the man page to add the new subcommand:

https://github.com/clearlinux/swupd-client/blob/master/docs/swupd.1.md

**Comment by bryteise** [comment]
It would be nice if the new subcommand got the bundle-add --list-bundles feature added to it as well (as an option) to keep the very similar features in a single place. Note this causes the need for the bundle-list subcommand to support a lot of the other common swupd options.

Should have tests for this change too.

**Comment by phmccarty** [comment]
@bryteise I like that idea. `bundle-list` lists the installed bundles, and `bundle-list --all` could list all available bundles, with identical output to `bundle-add --list`.

**Comment by MarioCarrilloA** [comment]
Thank you so much for feedback, I am going to work in a new commit about man page, and once these changes are merged, I am going to work in to move _bundle-add --list_ to _bundle-list_ sub-command :)

**Comment by MarioCarrilloA** [comment]
@phmccarty @sofar @bryteise documentation commit done :)

**Comment by sofar** [comment]
I'm OK with this as-is, but the question remains who will add the requested additional `--all` command.

**Comment by MarioCarrilloA** [comment]
@sofar I will add it, once this request has been merged :)

**Pull request merged**
