### PR TITLE
Fix memleak in query_total_download_size()

### PR DESCRIPTION
**Pull request by bradTpeters**
Signed-off-by: Brad T. Peters <brad.t.peters@intel.com>

### CODE REVIEW

**Comment by phmccarty** [comment]
+1 looks good

**Comment by tpepper** [comment]
The commit message is lacking here.  It should include a fixes issue 89 indicator.

Except it only fixes one of the four leaks.

**Comment by bradTpeters** [comment]
It fixes 3 of 4; looking at the 4th now

**Comment by bradTpeters** [comment]
One additional free() added to address the 4th issue

**Comment by tpepper** [comment]
The latest iteration of the PR has a bunch of memory management issues:

```
==8919== Memcheck, a memory error detector
==8919== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==8919== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==8919== Command: /usr/local/bin/swupd search -p ./foo -F staging -u http://clearlinux-sandbox.jf.intel.com/update/ AAAAAAAAAAA
==8919== 
Attempting to download version string to memory
Searching for 'AAAAAAAAAAA'

Signature check succeeded.
==8919== Invalid read of size 8
==8919==    at 0x404923: do_search (search.c:271)
==8919==    by 0x405369: search_main (search.c:522)
==8919==    by 0x61B757F: (below main) (in /usr/lib64/libc-2.22.so)
==8919==  Address 0xa1e5d48 is 24 bytes inside a block of size 56 free'd
==8919==    at 0x4C29CF0: free (vg_replace_malloc.c:530)
==8919==    by 0x404ECD: download_manifests (search.c:472)
==8919==    by 0x4052BA: search_main (search.c:502)
==8919==    by 0x61B757F: (below main) (in /usr/lib64/libc-2.22.so)
==8919==  Block was alloc'd at
==8919==    at 0x4C2A988: calloc (vg_replace_malloc.c:711)
==8919==    by 0x4E3F061: alloc_manifest (manifest.c:154)
==8919==    by 0x4E3F061: manifest_from_file (manifest.c:244)
==8919==    by 0x4E400DD: load_mom (manifest.c:597)
==8919==    by 0x404C38: download_manifests (search.c:412)
==8919==    by 0x4052BA: search_main (search.c:502)
==8919==    by 0x61B757F: (below main) (in /usr/lib64/libc-2.22.so)
==8919== 
==8919== Invalid read of size 8
==8919==    at 0x4E3D1BF: verify_bundle_hash (hash.c:262)
==8919==    by 0x4E4016E: load_manifest (manifest.c:635)
==8919==    by 0x40497F: do_search (search.c:278)
==8919==    by 0x405369: search_main (search.c:522)
==8919==    by 0x61B757F: (below main) (in /usr/lib64/libc-2.22.so)
==8919==  Address 0xa1e5d48 is 24 bytes inside a block of size 56 free'd
==8919==    at 0x4C29CF0: free (vg_replace_malloc.c:530)
==8919==    by 0x404ECD: download_manifests (search.c:472)
==8919==    by 0x4052BA: search_main (search.c:502)
==8919==    by 0x61B757F: (below main) (in /usr/lib64/libc-2.22.so)
==8919==  Block was alloc'd at
==8919==    at 0x4C2A988: calloc (vg_replace_malloc.c:711)
==8919==    by 0x4E3F061: alloc_manifest (manifest.c:154)
==8919==    by 0x4E3F061: manifest_from_file (manifest.c:244)
==8919==    by 0x4E400DD: load_mom (manifest.c:597)
==8919==    by 0x404C38: download_manifests (search.c:412)
==8919==    by 0x4052BA: search_main (search.c:502)
==8919==    by 0x61B757F: (below main) (in /usr/lib64/libc-2.22.so)
==8919== 
==8919== Invalid read of size 8
==8919==    at 0x4E3E9D3: list_head (list.c:164)
==8919==    by 0x4E3D1C7: verify_bundle_hash (hash.c:262)
==8919==    by 0x4E4016E: load_manifest (manifest.c:635)
==8919==    by 0x40497F: do_search (search.c:278)
==8919==    by 0x405369: search_main (search.c:522)
==8919==    by 0x61B757F: (below main) (in /usr/lib64/libc-2.22.so)
==8919==  Address 0xf8 is not stack'd, malloc'd or (recently) free'd
==8919== 
==8919== 
==8919== Process terminating with default action of signal 11 (SIGSEGV)
==8919==  Access not within mapped region at address 0xF8
==8919==    at 0x4E3E9D3: list_head (list.c:164)
==8919==    by 0x4E3D1C7: verify_bundle_hash (hash.c:262)
==8919==    by 0x4E4016E: load_manifest (manifest.c:635)
==8919==    by 0x40497F: do_search (search.c:278)
==8919==    by 0x405369: search_main (search.c:522)
==8919==    by 0x61B757F: (below main) (in /usr/lib64/libc-2.22.so)
==8919==  If you believe this happened as a result of a stack
==8919==  overflow in your program's main thread (unlikely but
==8919==  possible), you can try to increase the size of the
==8919==  main thread stack using the --main-stacksize= flag.
==8919==  The main thread stack size used in this run was 8388608.
==8919== 
==8919== HEAP SUMMARY:
==8919==     in use at exit: 225,905 bytes in 4,137 blocks
==8919==   total heap usage: 319,890 allocs, 315,753 frees, 26,077,899 bytes allocated
==8919== 
==8919== 4 bytes in 1 blocks are definitely lost in loss record 8 of 871
==8919==    at 0x4C28BF6: malloc (vg_replace_malloc.c:299)
==8919==    by 0x62213D9: strdup (in /usr/lib64/libc-2.22.so)
==8919==    by 0x4E3F07A: alloc_manifest (manifest.c:160)
==8919==    by 0x4E3F07A: manifest_from_file (manifest.c:244)
==8919==    by 0x4E400DD: load_mom (manifest.c:597)
==8919==    by 0x404C38: download_manifests (search.c:412)
==8919==    by 0x4052BA: search_main (search.c:502)
==8919==    by 0x61B757F: (below main) (in /usr/lib64/libc-2.22.so)
==8919== 
==8919== 1,181 bytes in 22 blocks are definitely lost in loss record 841 of 871
==8919==    at 0x4C2AB8B: realloc (vg_replace_malloc.c:785)
==8919==    by 0x62AAB1C: __vasprintf_chk (in /usr/lib64/libc-2.22.so)
==8919==    by 0x4E3D43E: vasprintf (stdio2.h:210)
==8919==    by 0x4E3D43E: string_or_die (helpers.c:651)
==8919==    by 0x404CCB: query_total_download_size (search.c:364)
==8919==    by 0x404CCB: download_manifests (search.c:421)
==8919==    by 0x4052BA: search_main (search.c:502)
==8919==    by 0x61B757F: (below main) (in /usr/lib64/libc-2.22.so)
==8919== 
==8919== 4,690 bytes in 110 blocks are definitely lost in loss record 867 of 871
==8919==    at 0x4C28BF6: malloc (vg_replace_malloc.c:299)
==8919==    by 0x62AAB47: __vasprintf_chk (in /usr/lib64/libc-2.22.so)
==8919==    by 0x4E3D43E: vasprintf (stdio2.h:210)
==8919==    by 0x4E3D43E: string_or_die (helpers.c:651)
==8919==    by 0x404CCB: query_total_download_size (search.c:364)
==8919==    by 0x404CCB: download_manifests (search.c:421)
==8919==    by 0x4052BA: search_main (search.c:502)
==8919==    by 0x61B757F: (below main) (in /usr/lib64/libc-2.22.so)
==8919== 
==8919== LEAK SUMMARY:
==8919==    definitely lost: 5,875 bytes in 133 blocks
==8919==    indirectly lost: 0 bytes in 0 blocks
==8919==      possibly lost: 0 bytes in 0 blocks
==8919==    still reachable: 220,030 bytes in 4,004 blocks
==8919==         suppressed: 0 bytes in 0 blocks
==8919== Reachable blocks (those to which a pointer was found) are not shown.
==8919== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==8919== 
==8919== For counts of detected and suppressed errors, rerun with: -v
==8919== ERROR SUMMARY: 18 errors from 6 contexts (suppressed: 0 from 0)
Segmentation fault
```

**Comment by bradTpeters** [comment]
Just added a fix for the original 3 or 4 leaks; I'll look into the above regressions more tomorrow; spent the wkend getting over a bug, and it seems I'm not quite fully over it

**Pull request closed without merging**
