### PR TITLE
Fixed: Correctly show installed bundles

### PR DESCRIPTION
**Pull request by lebensterben**
This fixed the `zsh` completion.

Previously some installed bundles are not shown for
`swupd bundle-remove` and `swupd diagnose --bundles=`,
it is fixed.

### CODE REVIEW

**Comment by lebensterben** [comment]
Yes indeed the history is messed up.

How to fix this? `git rebase -i ` and `git push --force` ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by miguelinux** [comment]
> How to fix this? `git rebase -i ` and `git push --force` ?

Yes

**Comment by lebensterben** [comment]
Well I was struggling with `git` and hopefully this looks clear enough.

**Comment by lebensterben** [comment]
I made a new Pull Request #982 whose commit history should be clean.

**Pull request closed without merging**
